export const battlechipStats = {
    // Cannon line
    "Cannon": {
        name: "Cannon",
        type: "attack",
        element: "norm",
        area: "Gun",
        delay: 300,
        damage: 40,
        cooldown: 2000,
        evolution: "HiCannon",
        image: "Cannon",
    },
    "HiCannon": {
        name: "High Cannon",
        type: "attack",
        element: "norm",
        area: "Gun",
        delay: 250,
        damage: 80,
        cooldown: 3000,
        evolution: "M-Cannon",
        image: "HiCannon",
    },
    "M-Cannon": {
        name: "Mega Cannon",
        type: "attack",
        element: "norm",
        area: "Gun",
        delay: 200,
        damage: 120,
        cooldown: 4000,
        evolution: null,
        image: "M-Cannon",
    },
    // Shotgun line
    "Shotgun": {
        name: "Shotgun",
        type: "attack",
        element: "norm",
        area: "Shotgun",
        delay: 300,
        damage: 30,
        cooldown: 2000,
        evolution: "SideGun",
        image: "Shotgun",
    },
    "SideGun": {
        name: "Side  Gun",
        type: "attack",
        element: "norm",
        area: "SideGun",
        delay: 300,
        damage: 30,
        cooldown: 2000,
        evolution: "CrossGun",
        image: "SideGun",
    },
    "CrossGun": {
        name: "Cross Gun",
        type: "attack",
        element: "norm",
        area: "CrossGun",
        delay: 300,
        damage: 30,
        cooldown: 2500,
        evolution: null,
        image: "CrossGun",
    },
    // Sword line
    "Sword": {
        name: "Sword",
        type: "attack",
        element: "norm",
        area: "Melee",
        delay: 180,
        damage: 80,
        cooldown: 4000,
        evolution: "WideSword",
        image: "Sword",
    },
    "WideSword": {
        name: "Wide Sword",
        type: "attack",
        element: "norm",
        area: "WideMelee",
        delay: 180,
        damage: 80,
        cooldown: 4500,
        evolution: "LongSword",
        image: "WideSword",
    },
    "LongSword": {
        name: "Long Sword",
        type: "attack",
        element: "norm",
        area: "LongMelee",
        delay: 180,
        damage: 80,
        cooldown: 4500,
        evolution: null,
        image: "LongSowrd",
    }
}